
services:
  db:
    image: postgres
    
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - "5434:5432"

    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
